/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Saurin' at '12/16/15 9:29 PM' with Gradle 2.9
 *
 * @author Saurin, @date 12/16/15 9:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
